CREATE TABLE IF NOT EXISTS ecl_runs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  run_key VARCHAR(255) NOT NULL UNIQUE,
  date DATE NOT NULL,
  status VARCHAR(50) NOT NULL,
  approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 